function About(){
    return <div>
        <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto eaque dolorum ea dolore voluptatem blanditiis repellendus laudantium similique ratione in. Fugit voluptatum nihil totam tenetur? Molestias beatae deserunt a voluptate. Odio commodi debitis illum placeat inventore delectus cumque quas velit, ex, blanditiis nobis fugit! Deserunt vitae repellendus rem aspernatur nemo? Iusto veritatis dicta sit neque voluptates eius facere aut aperiam, placeat in ab saepe! Reprehenderit maiores magnam praesentium et nulla quos voluptates odit ad nam, doloribus, fugit, cumque quibusdam quia quam id vel minus. Placeat doloribus aspernatur expedita, fugiat error consequatur nesciunt omnis odio voluptates quis animi sapiente mollitia explicabo?</div>
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti asperiores sed architecto amet consequuntur numquam et atque saepe esse neque accusantium, laboriosam nisi possimus nulla velit nesciunt reprehenderit in obcaecati exercitationem expedita. A hic distinctio dignissimos quis nisi delectus tempora eveniet vero unde error quam debitis recusandae ab excepturi animi provident dolorum, minus iusto laudantium exercitationem. Expedita, quas? Incidunt, doloribus? Molestiae consequuntur praesentium nisi dolore non a eligendi eos tempora totam autem reiciendis perspiciatis consequatur soluta inventore harum maiores, sapiente iusto. Quidem blanditiis enim tenetur est animi aperiam odit quis dolorum sit quaerat quam quod quisquam quibusdam, magni aliquam voluptates.
        </div>
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium natus perferendis sit laudantium adipisci veritatis neque placeat incidunt nisi similique ullam recusandae, esse eligendi repudiandae, minus porro corrupti assumenda officia explicabo quod nam molestiae eius officiis quaerat! Iste ducimus, omnis explicabo ex similique deleniti. Explicabo, sunt temporibus? Aperiam perspiciatis ratione quas. Quos sunt accusantium laudantium odit ab beatae sapiente magnam natus nostrum totam molestias, iusto repudiandae ullam, tenetur unde. Pariatur vel eius explicabo recusandae? Obcaecati totam consectetur cumque sed praesentium, rerum deserunt, laudantium, autem tempora tempore corporis a vitae distinctio mollitia assumenda esse pariatur enim fugiat perferendis aut nemo ratione?
        </div>
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident illum explicabo vitae veritatis neque. Amet voluptates id placeat tempora, doloremque earum iste alias exercitationem explicabo beatae magnam facilis nemo dolore hic debitis in doloribus! Est, aliquam dignissimos odio iste dolor nisi numquam veritatis ducimus, dolores voluptates et ipsum ex dicta vel mollitia soluta. Provident illum repellendus saepe ea voluptatem laudantium et, eligendi excepturi, vero neque fugiat minus tempora culpa sint pariatur autem tempore quos veritatis! Dolorem ullam necessitatibus natus itaque iste soluta, officia dolore eius optio aliquid non recusandae voluptatem porro maiores quo, dolores quisquam deleniti ducimus perferendis. Doloremque, accusantium.
        </div>
    </div>
}
export default About;